[package]
name = "mavlink_parser_vest"
version = "0.1.0"
edition = "2024"

[dependencies]
vstd = { version = "=0.0.0-2026-08-23-0033", default-features=false }
verus_builtin = { version = "=0.0.0-2026-08-09-0044" }
verus_builtin_macros = { version = "=0.0.0-2026-08-23-0033" }
vest_lib = { git = "https://github.com/secure-foundations/vest", rev = "e0671fbbec7c7a4daeb5581fd12d21ec89ec005c", default-features = false, features = ["alloc"] }

[package.metadata.verus]
verify = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(verus_keep_ghost)"] }
