# Do not edit this file as it will be overwritten if HAMR codegen is rerun

SDDF ?= $(LIONSOS)/dep/sddf
override SDDF := $(abspath $(SDDF))
ifeq ("$(wildcard $(SDDF)/util/util.mk)","")
$(error Set SDDF to a copy of https://github.com/au-ts/sddf, or LIONSOS to a checkout that vendors it at dep/sddf)
endif


# Metaprogram that generates the system description file.
# Override to use an alternative schedule (e.g. monitor.mk).
MSD ?= $(TOP_DIR)/meta.py

# Header files containing config structs whose sizes the sdfgen helper
# needs to calculate. Override to point at a different config header.
SCHEDULER_CONFIG_HEADERS ?= $(TOP_DIR)/scheduler/include/default.user_config.h

# Scheduler C source file compiled into scheduler.elf.
# Override to substitute a different scheduler implementation
# (e.g. one that publishes schedule state for runtime monitoring).
SCHEDULER_C ?= $(TOP_DIR)/scheduler/src/default.scheduler.c


TOOLCHAIN := clang
CC := clang
LD := ld.lld
RANLIB := llvm-ranlib
AR := llvm-ar
OBJCOPY := llvm-objcopy
MICROKIT_TOOL ?= $(MICROKIT_SDK)/bin/microkit
DTC := dtc
PYTHON ?= python3

SYSTEM_FILE := arinc_scheduling.system
IMAGE_FILE := loader.img
REPORT_FILE := report.txt

SUPPORTED_BOARDS := qemu_virt_aarch64

include ${SDDF}/tools/make/board/common.mk

SDFGEN_HELPER := $(TOP_DIR)/sdfgen_helper.py

# Macros needed by sdfgen helper to calculate config struct sizes
SDFGEN_UNKOWN_MACROS := MAX_PARTITIONS=61 MAX_SCHEDULE_SLOTS=128

SDDF_CUSTOM_LIBC := 1

LDFLAGS := -L$(BOARD_DIR)/lib -L$(SDDF)/lib
LIBS := -lmicrokit -Tmicrokit.ld libsddf_util_debug.a

SDDF_MAKEFILES := ${SDDF}/util/util.mk \
	${SDDF}/drivers/timer/${TIMER_DRIV_DIR}/timer_driver.mk \
	${SDDF}/drivers/serial/${UART_DRIV_DIR}/serial_driver.mk \
	${SDDF}/serial/components/serial_components.mk

include ${SDDF_MAKEFILES}

# exporting TOP_TYPES_INCLUDE in case other makefiles need it
export TOP_TYPES_INCLUDE = -I$(TOP_DIR)/types/include

CFLAGS += \
	-I$(SDDF)/include \
	-I$(SDDF)/include/microkit \
	-I$(TOP_DIR)/scheduler/include \
	$(TOP_TYPES_INCLUDE) \
	-I$(TOP_DIR)/components/seL4_MavlinkFirewall_MavlinkFirewall/include \
	-I$(TOP_DIR)/components/seL4_RxFirewall_RxFirewall/include \
	-I$(TOP_DIR)/components/seL4_TxFirewall_TxFirewall/include \
	-I$(TOP_DIR)/components/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver/include \
	-I$(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/include


UTIL_OBJS :=

TYPE_OBJS := \
	sb_queue_SW_RawEthernetMessage_1.o \
	sb_queue_SW_UdpFrame_Impl_1.o \
	sb_queue_SW_SizedEthernetMessage_Impl_1.o


all: cache.o

# Sentinel file whose name encodes a hash of build-affecting variables.
# When any of these change the old sentinel is removed and a new one is created,
# forcing dependent targets to rebuild.
CHECK_FLAGS_BOARD_MD5:=.board_cflags-$(shell echo -- ${CFLAGS} ${BOARD} ${MICROKIT_CONFIG} ${MICROKIT_SDK} ${MSD} ${SCHEDULER_C} ${SCHEDULER_CONFIG_HEADERS}| shasum | sed 's/ *-//')

${CHECK_FLAGS_BOARD_MD5}:
	-rm -f .board_cflags-*
	touch $@


vpath %.c $(SDDF) \
	$(TOP_DIR)/scheduler/src \
	$(TOP_DIR)/types/src \
	$(TOP_DIR)/components/seL4_MavlinkFirewall_MavlinkFirewall/src \
	$(TOP_DIR)/components/seL4_RxFirewall_RxFirewall/src \
	$(TOP_DIR)/components/seL4_TxFirewall_TxFirewall/src \
	$(TOP_DIR)/components/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver/src \
	$(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/src


IMAGES := timer_driver.elf scheduler.elf \
	seL4_MavlinkFirewall_MavlinkFirewall.elf \
	seL4_MavlinkFirewall_MavlinkFirewall_MON.elf \
	seL4_RxFirewall_RxFirewall.elf \
	seL4_RxFirewall_RxFirewall_MON.elf \
	seL4_TxFirewall_TxFirewall.elf \
	seL4_TxFirewall_TxFirewall_MON.elf \
	seL4_LowLevelEthernetDriver_LowLevelEthernetDriver.elf \
	seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_MON.elf \
	seL4_ArduPilot_ArduPilot.elf \
	seL4_ArduPilot_ArduPilot_MON.elf

${IMAGES}: libsddf_util_debug.a ${CHECK_FLAGS_BOARD_MD5}


# user code
seL4_MavlinkFirewall_MavlinkFirewall_rust:
	make -C ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall $(RUST_MAKE_TARGET)

# user code
seL4_RxFirewall_RxFirewall_rust:
	make -C ${CRATES_DIR}/seL4_RxFirewall_RxFirewall $(RUST_MAKE_TARGET)

# user code
seL4_TxFirewall_TxFirewall_rust:
	make -C ${CRATES_DIR}/seL4_TxFirewall_TxFirewall $(RUST_MAKE_TARGET)

# user code
seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_rust:
	make -C ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver $(RUST_MAKE_TARGET)

# monitor
seL4_ArduPilot_ArduPilot_MON.o: $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/src/seL4_ArduPilot_ArduPilot_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/include

# seL4_ArduPilot_ArduPilot.a contains a VM
.PHONY: seL4_ArduPilot_ArduPilot.a
seL4_ArduPilot_ArduPilot.a:
ifeq (, $(wildcard $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/board/$(MICROKIT_BOARD)/Makefile))
	$(error Didn't find: $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/board/$(MICROKIT_BOARD)/Makefile);
endif
	mkdir -p $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/build
	cp $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/board/${MICROKIT_BOARD}/Makefile $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/build
	make -C $(TOP_DIR)/components/seL4_ArduPilot_ArduPilot/build


%.o: %.c ${SDDF}/include
	${CC} ${CFLAGS} -c -o $@ $<

SCHEDULER_OBJ := $(notdir $(basename $(SCHEDULER_C))).o

$(SCHEDULER_OBJ): $(SCHEDULER_C) ${SDDF}/include
	${CC} ${CFLAGS} -c -o $@ $<

scheduler.elf: $(UTIL_OBJS) $(TYPE_OBJS) $(SCHEDULER_OBJ) ${CHECK_FLAGS_BOARD_MD5}
	$(LD) $(LDFLAGS) $(filter %.o, $^) $(LIBS) -o $@

seL4_MavlinkFirewall_MavlinkFirewall_MON.elf: seL4_MavlinkFirewall_MavlinkFirewall_MON_user.o seL4_MavlinkFirewall_MavlinkFirewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_MavlinkFirewall_MavlinkFirewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_MavlinkFirewall_MavlinkFirewall_rust seL4_MavlinkFirewall_MavlinkFirewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_MavlinkFirewall_MavlinkFirewall -o $@

seL4_RxFirewall_RxFirewall_MON.elf: seL4_RxFirewall_RxFirewall_MON_user.o seL4_RxFirewall_RxFirewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_RxFirewall_RxFirewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_RxFirewall_RxFirewall_rust seL4_RxFirewall_RxFirewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_RxFirewall_RxFirewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_RxFirewall_RxFirewall -o $@

seL4_TxFirewall_TxFirewall_MON.elf: seL4_TxFirewall_TxFirewall_MON_user.o seL4_TxFirewall_TxFirewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_TxFirewall_TxFirewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_TxFirewall_TxFirewall_rust seL4_TxFirewall_TxFirewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_TxFirewall_TxFirewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_TxFirewall_TxFirewall -o $@

seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_MON.elf: seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_MON_user.o seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_LowLevelEthernetDriver_LowLevelEthernetDriver.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_LowLevelEthernetDriver_LowLevelEthernetDriver_rust seL4_LowLevelEthernetDriver_LowLevelEthernetDriver.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_LowLevelEthernetDriver_LowLevelEthernetDriver -o $@

seL4_ArduPilot_ArduPilot_MON.elf: seL4_ArduPilot_ArduPilot_MON_user.o seL4_ArduPilot_ArduPilot_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_ArduPilot_ArduPilot.elf: $(TYPE_OBJS) seL4_ArduPilot_ArduPilot.a
	$(LD) $(LDFLAGS) $^ --start-group -lmicrokit -Tmicrokit.ld seL4_ArduPilot_ArduPilot.a --end-group -o $@



$(SYSTEM_FILE): $(IMAGES) $(DTB) ${CHECK_FLAGS_BOARD_MD5}
	$(PYTHON) $(SDFGEN_HELPER) --macros "$(SDFGEN_UNKOWN_MACROS)" --configs "$(SCHEDULER_CONFIG_HEADERS)" --output $(TOP_BUILD_DIR)/config_structs.py
	$(PYTHON) $(MSD) --sddf $(SDDF) --board $(MICROKIT_BOARD) --dtb $(DTB) --output . --sdf $(SYSTEM_FILE) --objcopy $(OBJCOPY)
	$(OBJCOPY) --update-section .device_resources=timer_driver_device_resources.data timer_driver.elf
	$(OBJCOPY) --update-section .timer_client_config=timer_client_scheduler.data scheduler.elf

$(IMAGE_FILE) $(REPORT_FILE): $(IMAGES) $(SYSTEM_FILE)
	$(MICROKIT_TOOL) $(SYSTEM_FILE) --search-path $(TOP_BUILD_DIR) --board $(MICROKIT_BOARD) --config $(MICROKIT_CONFIG) -o $(IMAGE_FILE) -r $(REPORT_FILE)


FORCE:

qemu:
	$(QEMU) -nographic $(QEMU_ARCH_ARGS)

clean::
	${RM} -f *.elf .depend* $
	find . -name \*.[do] |xargs --no-run-if-empty rm

clobber:: clean
	rm -f *.a
	rm -f ${IMAGE_FILE} ${REPORT_FILE}

test:: 
	make -C ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall test
	make -C ${CRATES_DIR}/seL4_RxFirewall_RxFirewall test
	make -C ${CRATES_DIR}/seL4_TxFirewall_TxFirewall test
	make -C ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver test

clean:: 
	make -C ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall clean
	make -C ${CRATES_DIR}/seL4_RxFirewall_RxFirewall clean
	make -C ${CRATES_DIR}/seL4_TxFirewall_TxFirewall clean
	make -C ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver clean
	rm -rf ${TOP_DIR}/components/seL4_ArduPilot_ArduPilot/build

verus: 
	make -C ${CRATES_DIR}/seL4_MavlinkFirewall_MavlinkFirewall verus
	make -C ${CRATES_DIR}/seL4_RxFirewall_RxFirewall verus
	make -C ${CRATES_DIR}/seL4_TxFirewall_TxFirewall verus
	make -C ${CRATES_DIR}/seL4_LowLevelEthernetDriver_LowLevelEthernetDriver verus
