#pragma once

#if __has_include(<libvmm/util/util.h>)
#include <libvmm/util/util.h>
#elif __has_include(<sddf/util/util.h>)
#include <sddf/util/printf.h>
#include <sddf/util/util.h>
#define printf sddf_dprintf
#else
#include <printf.h>
#endif

#include <stddef.h>

// These match musl's prototypes, so re-declaring them is harmless where sddf's
// custom libc is on the include path too.
void *memcpy(void *restrict dest, const void *restrict src, size_t n);
void *memset(void *dest, int c, size_t n);

#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool put_EthernetFramesTxOut0(const SW_SizedEthernetMessage_Impl *data);
bool put_EthernetFramesTxOut1(const SW_SizedEthernetMessage_Impl *data);
bool put_EthernetFramesTxOut2(const SW_SizedEthernetMessage_Impl *data);
bool put_EthernetFramesTxOut3(const SW_SizedEthernetMessage_Impl *data);
bool EthernetFramesTxIn0_is_empty(void);
bool get_EthernetFramesTxIn0_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_EthernetFramesTxIn0(SW_RawEthernetMessage *data);
bool EthernetFramesTxIn1_is_empty(void);
bool get_EthernetFramesTxIn1_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_EthernetFramesTxIn1(SW_RawEthernetMessage *data);
bool EthernetFramesTxIn2_is_empty(void);
bool get_EthernetFramesTxIn2_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_EthernetFramesTxIn2(SW_RawEthernetMessage *data);
bool EthernetFramesTxIn3_is_empty(void);
bool get_EthernetFramesTxIn3_poll(sb_event_counter_t *numDropped, SW_RawEthernetMessage *data);
bool get_EthernetFramesTxIn3(SW_RawEthernetMessage *data);
